### ISSUE TITLE
replace cartography by mapsf

### ISSUE THREAD

**Issue by rCarto** [InseeFrLab/btb#1]
I suggest to replace `cartography` by `mapsf` in examples. 
See: https://github.com/riatelab/cartography#consider-mapsf
Would you be interested by a PR?

**Comment by RLesur** [comment]
Thanks a lot for the suggestion, @rCarto!
I am very sorry but for now, this repository is just a mirror. We are working with the original authors to make this repository the official one.
Apologies, but for the moment, this is not the official way for sending pull requests. 
In order to get in touch with `{btb}` maintainers, I suggest you to send them an email.

**Comment by rCarto** [comment]
J'avais un doute justement :-)
